### ISSUE TITLE
py-ard fails for IMGT release 3480

### ISSUE THREAD

**Issue by pbashyal-nmdp** [nmdp-bioinformatics/py-ard#163]
py-ard fails importing IMGT release 3480
```
 $ pyard-import --db-version 3480
Importing IMGT database version: 3480
Traceback (most recent call last):
  File "/private/tmp/pyard-test/venv/bin/pyard-import", line 112, in <module>
    ard = pyard.ARD(imgt_version=imgt_version, data_dir=data_dir)
  File "/private/tmp/pyard-test/venv/lib/python3.9/site-packages/pyard/pyard.py", line 105, in __init__
    dr.generate_alleles_and_xx_codes_and_who(self.db_connection, imgt_version, self.ars_mappings)
  File "/private/tmp/pyard-test/venv/lib/python3.9/site-packages/pyard/data_repository.py", line 230, in generate_alleles_and_xx_codes_and_who
    allele_df = pd.read_csv(allele_list_url, header=6, usecols=['Allele'])
  File "/private/tmp/pyard-test/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/private/tmp/pyard-test/venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
```

The issue seems to be the 3480 is missing in `Latest/allelelist/Allelelist.{imgt_version}.txt` directory. Filed an issue with IMGT https://github.com/ANHIG/IMGTHLA/issues/302

**Comment by pbashyal-nmdp** [comment]
File is back in IMGT/HLA repo.
