### ISSUE TITLE
Issue with running on AWS ec2

### ISSUE THREAD

**Issue by rsajulga-nmdp** [nmdp-bioinformatics/py-ard#177]
Specifying a version throws an error.

```
>>> from pyard import ARD
>>> ARD('3490')
Traceback (most recent call last):
  File "/home/centos/bin/anaconda3/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/centos/bin/anaconda3/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/centos/bin/anaconda3/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/centos/bin/anaconda3/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/centos/bin/anaconda3/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/home/centos/bin/anaconda3/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/home/centos/bin/anaconda3/lib/python3.8/http/client.py", line 1409, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/home/centos/bin/anaconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/centos/bin/anaconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/centos/bin/anaconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable toget local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/centos/Projects/agg-matcher/analysis/venv/lib/python3.8/site-packages/pyard/pyard.py", line 102, in __init__
    dr.generate_mac_codes(self.db_connection, False)
  File "/home/centos/Projects/agg-matcher/analysis/venv/lib/python3.8/site-packages/pyard/data_repository.py", line 517, in generate_mac_codes
    df_mac = pd.read_csv(
  File "/home/centos/Projects/agg-matcher/analysis/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/centos/Projects/agg-matcher/analysis/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/centos/Projects/agg-matcher/analysis/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/centos/Projects/agg-matcher/analysis/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/centos/Projects/agg-matcher/analysis/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/home/centos/Projects/agg-matcher/analysis/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/home/centos/Projects/agg-matcher/analysis/venv/lib/python3.8/site-packages/pandas/io/common.py", line 558, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/centos/Projects/agg-matcher/analysis/venv/lib/python3.8/site-packages/pandas/io/common.py", line 289, in _get_filepath_or_buffer
    req = urlopen(filepath_or_buffer)
  File "/home/centos/Projects/agg-matcher/analysis/venv/lib/python3.8/site-packages/pandas/io/common.py", line 195, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/home/centos/bin/anaconda3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/centos/bin/anaconda3/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/centos/bin/anaconda3/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/centos/bin/anaconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/centos/bin/anaconda3/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/centos/bin/anaconda3/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
```

**Comment by mmaiers-nmdp** [comment]
This is issue #23.  Its not clear what the resolution was.  I think it requires setting an environment variable to run without a cert.

**Comment by mmaiers-nmdp** [comment]
Here are 4 ways to fix it https://www.howtouselinux.com/post/ssl-certificate_verify_failed-in-python

**Comment by rsajulga-nmdp** [comment]
Got it working after a bit of tweaking.

This seemed to be the ultimate solution: `pip install --upgrade --ignore-installed certifi`
