### ISSUE TITLE
handle invald alleles

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#18]
pyARD appears to fail ungracefully when reducing a glstring that contains in valid alleles
```
>>> ard.redux_gl("A*01:01:01:01^B*07:02:01", "G")
'A*01:01:01G^B*07:02:01G'
>>> ard.redux_gl("A*01:01:01:01^B*07:02:01:12", "G")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmaiers/src/git/pyARD-fork/venv/lib/python3.7/site-packages/pyard-0.0.10-py3.7.egg/pyard/pyard.py", line 393, in redux_gl
    return "^".join(sorted(set([self.redux_gl(a, redux_type) for a in glstring.split("^")]), key=functools.cmp_to_key(loci_sort)))
  File "/Users/mmaiers/src/git/pyARD-fork/venv/lib/python3.7/site-packages/pyard-0.0.10-py3.7.egg/pyard/pyard.py", line 57, in loci_sort
    lb = b.split(":")
AttributeError: 'NoneType' object has no attribute 'split'

```

This could be addressed by implementing glstring validation behavior (parallel redux or as part of it) and then graceful error handling.

It seems to deal with single alleles OK
```
>>> ard.redux("A*01:99:99", "G")
>>> ard.redux("A*01:99", "G")
'A*01:99'
```

and

```>>> ard.redux_gl("A*01:99", "G")
'A*01:99'
>>> ard.redux_gl("A*01:99:99", "G")
```

but when glstring characters are included (^, +, /, |) it fails

**Comment by pbashyal-nmdp** [comment]
Not an issue anymore with >= version `0.0.18`

```
>>> ard.redux_gl("A*01:01:01:01^B*07:02:01", "G")
'A*01:01:01G^B*07:02:01G'
>>> ard.redux_gl("A*01:01:01:01^B*07:02:01:12", "G")
''
```
