### ISSUE TITLE
problem with exception handling 

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#217]
pyard-reduce-csv crashes on an invalid allele

it appears to a problem with exception handling

```
(venv) A0507768:py-ard mmaiers$ pyard-reduce-csv -g
Created sample_reduce_conf.json
Created sample.csv
(venv) A0507768:py-ard mmaiers$ pyard-reduce-csv -c sample_reduce_conf.json 
Using config file: sample_reduce_conf.json
Column:r_a_typ1 =>
	A*01:AB => A*01:01/A*01:02
	A*01:01:42 => A*01:01
	A*02:247 => A*02:247
Column:r_a_typ2 =>
	A*29:79 => A*29:79
	A*30:12:02 => A*30:12
	A*03:227 => A*03:227
Column:r_b_typ1 =>
	B*18:67 => B*18:67
	B*44:02:32 => B*44:02
	B*15:570 => B*15:570
Column:r_b_typ2 =>
	B*51:275 => B*51:275
	B*35:42 => B*35:01
	B*07:02:01:17 => B*07:02
Column:r_c_typ1 =>
	C*05:01:19 => C*05:01
	C*03:148 => C*03:148
	C*16:01:10 => C*16:01
Column:r_c_typ2 =>
Traceback (most recent call last):
  File "/Users/mmaiers/tmp/p/venv/bin/pyard-reduce-csv", line 123, in reduce
    reduced_allele = ard.redux(locus_allele, ard_config["redux_type"])
  File "/Users/mmaiers/tmp/p/venv/lib/python3.10/site-packages/pyard/ard.py", line 301, in redux
    self.validate(glstring)
  File "/Users/mmaiers/tmp/p/venv/lib/python3.10/site-packages/pyard/ard.py", line 392, in validate
    raise InvalidTypingError(
pyard.exceptions.InvalidTypingError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mmaiers/tmp/p/venv/bin/pyard-reduce-csv", line 286, in <module>
    df[column].apply(clean_locus, locus=locus, column_name=column),
  File "/Users/mmaiers/tmp/p/venv/lib/python3.10/site-packages/pandas/core/series.py", line 4771, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/Users/mmaiers/tmp/p/venv/lib/python3.10/site-packages/pandas/core/apply.py", line 1123, in apply
    return self.apply_standard()
  File "/Users/mmaiers/tmp/p/venv/lib/python3.10/site-packages/pandas/core/apply.py", line 1174, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2924, in pandas._libs.lib.map_infer
  File "/Users/mmaiers/tmp/p/venv/lib/python3.10/site-packages/pandas/core/apply.py", line 142, in f
    return func(x, *args, **kwargs)
  File "/Users/mmaiers/tmp/p/venv/bin/pyard-reduce-csv", line 166, in clean_locus
    return reduce(allele, locus, column_name)
  File "/Users/mmaiers/tmp/p/venv/bin/pyard-reduce-csv", line 126, in reduce
    print(e)
  File "/Users/mmaiers/tmp/p/venv/lib/python3.10/site-packages/pyard/exceptions.py", line 31, in __str__
    return f"Invalid HLA Typing: {self.message}"
AttributeError: 'InvalidTypingError' object has no attribute 'message'
```

**Comment by pbashyal-nmdp** [comment]
This has been fixed with the `1.0.0rc2`. Please upgrade and try again.
