### ISSUE TITLE
Allele Redux fails when running without MAC codes

### ISSUE THREAD

**Issue by pbashyal-nmdp** [nmdp-bioinformatics/py-ard#247]
In some instances, we don't need to use MAC codes. To support this use case, `py-ard` has the `load_mac` flag. This mode should not fail to reduce regular alleles.

```
>>> import pyard
>>> ard = pyard.init(3350, load_mac=False)
>>> ard.redux('A*01:01:01', 'lgx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/py-ard/venv/lib/python3.11/site-packages/pyard/ard.py", line 337, in redux
    self.validate(glstring)
  File "/private/tmp/py-ard/venv/lib/python3.11/site-packages/pyard/ard.py", line 428, in validate
    return self._is_valid_gl(glstring)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/py-ard/venv/lib/python3.11/site-packages/pyard/ard.py", line 683, in _is_valid_gl
    is_valid_allele = self._is_valid(glstring)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/py-ard/venv/lib/python3.11/site-packages/pyard/ard.py", line 637, in _is_valid
    not self.is_mac(allele)
        ^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/py-ard/venv/lib/python3.11/site-packages/pyard/ard.py", line 476, in is_mac
    return db.is_valid_mac_code(self.db_connection, code)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/py-ard/venv/lib/python3.11/site-packages/pyard/db.py", line 165, in is_valid_mac_code
    cursor = connection.execute(mac_query, (code,))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: mac_codes
```

**Comment by pbashyal-nmdp** [comment]
Fixed with PR #248 and is part of `1.0.2` release.

```
>>> import pyard
>>> pyard.__version__
'1.0.2'
>>> ard = pyard.init(3340, load_mac=False)
Creating /var/folders/nm/nyjkgrfn3fg207v5z5rz1w8m0000gp/T/pyard/pyard-3340.sqlite3 as cache.
Version: 3340
>>> ard.redux('A*01:01:01', 'lgx')
'A*01:01'
>>>
```
