### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by rsajulga-nmdp** [nmdp-bioinformatics/py-ard#250]
Regarding pyard (v1.0.0)...
```
>>> import pyard
>>> pyard.init()
```

```
Creating /tmp/pyard/pyard-Latest.sqlite3 as cache.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rsajulga/.conda/envs/pyard/lib/python3.9/site-packages/pyard/__init__.py", line 42, in init
    ard = ARD(
  File "/home/rsajulga/.conda/envs/pyard/lib/python3.9/site-packages/pyard/ard.py", line 92, in __init__
    self.db_connection, _ = db.create_db_connection(data_dir, imgt_version)
  File "/home/rsajulga/.conda/envs/pyard/lib/python3.9/site-packages/pyard/db.py", line 75, in create_db_connection
    return sqlite3.connect(file_uri, uri=True), db_filename
sqlite3.OperationalError: unable to open database file
```

**Comment by pbashyal-nmdp** [comment]
Looks like a permission issue, specify your own data directory. 
```
pyard.init(data_dir='pyard/cache')
```
