### ISSUE TITLE
redux_gl works for lgx but not G

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#66]
```
ard.redux_gl("A*02:01/A*02:786", "lgx")
'A*02:01'

ard.redux_gl("A*02:01/A*02:786", "G")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/b/py-ard/pyard/pyard.py", line 173, in redux_gl
    key=functools.cmp_to_key(smart_sort_comparator)))
  File "/private/tmp/b/py-ard/pyard/smart_sort.py", line 76, in smart_sort_comparator
    a1_f3 = int(a1_fields[2])
ValueError: invalid literal for int() with base 10: '01/A*02'
```

**Comment by pbashyal-nmdp** [comment]
This is related to smart sort trying to sort a GL String. This is fixed in the upcoming PR.
