### ISSUE TITLE
redux_gl for serology leads to recursion error

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#74]
```>>> ard.redux_gl('HLA-A*10^HLA-A*9', 'lg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/Fat/Dropbox/MacBookPro/2020/src/git/py-ard/pyard/pyard.py", line 159, in redux_gl
    return "^".join(sorted(set([self.redux_gl(a, redux_type) for a in glstring.split("^")]),
  File "/Volumes/Fat/Dropbox/MacBookPro/2020/src/git/py-ard/pyard/pyard.py", line 159, in <listcomp>
    return "^".join(sorted(set([self.redux_gl(a, redux_type) for a in glstring.split("^")]),
  File "/Volumes/Fat/Dropbox/MacBookPro/2020/src/git/py-ard/pyard/pyard.py", line 180, in redux_gl
    return self.redux_gl(glstring, redux_type)
  File "/Volumes/Fat/Dropbox/MacBookPro/2020/src/git/py-ard/pyard/pyard.py", line 180, in redux_gl
    return self.redux_gl(glstring, redux_type)
  File "/Volumes/Fat/Dropbox/MacBookPro/2020/src/git/py-ard/pyard/pyard.py", line 180, in redux_gl
    return self.redux_gl(glstring, redux_type)
  [Previous line repeated 491 more times]
  File "/Volumes/Fat/Dropbox/MacBookPro/2020/src/git/py-ard/pyard/pyard.py", line 155, in redux_gl
    if not self.isvalid_gl(glstring):
  File "/Volumes/Fat/Dropbox/MacBookPro/2020/src/git/py-ard/pyard/pyard.py", line 394, in isvalid_gl
    return self.isvalid(glstring)
  File "/Volumes/Fat/Dropbox/MacBookPro/2020/src/git/py-ard/pyard/pyard.py", line 358, in isvalid
    if not self.is_mac(allele) and \
  File "/Volumes/Fat/Dropbox/MacBookPro/2020/src/git/py-ard/pyard/pyard.py", line 246, in is_mac
    return re.search(r":\D+", gl) is not None
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 291, in _compile
    if isinstance(flags, RegexFlag):
RecursionError: maximum recursion depth exceeded in __instancecheck__```

**Comment by pbashyal-nmdp** [comment]
Can you provide the problematic serology typing ? I'm not able to reproduce.
```
>>> import pyard
>>> ard = pyard.ARD()
>>> ard.redux_gl('3', 'lgx')
''
>>> ard.redux_gl('30', 'lgx')
''
>>> ard.redux_gl('s3', 'lgx')
''
```

**Comment by mmaiers-nmdp** [comment]
```ard.redux_gl('HLA-A*10^HLA-A*9', 'lg')```

**Comment by mmaiers-nmdp** [comment]
On a clean virtualenv Python 3.9:
```
>>> import pyard
>>> ard = pyard.ARD()
>>> ard.redux_gl('HLA-A*10^HLA-A*9', 'lg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmaiers/tmp/py-ard/venv/lib/python3.9/site-packages/pyard/pyard.py", line 159, in redux_gl
    return "^".join(sorted(set([self.redux_gl(a, redux_type) for a in glstring.split("^")]),
  File "/Users/mmaiers/tmp/py-ard/venv/lib/python3.9/site-packages/pyard/pyard.py", line 159, in <listcomp>
    return "^".join(sorted(set([self.redux_gl(a, redux_type) for a in glstring.split("^")]),
  File "/Users/mmaiers/tmp/py-ard/venv/lib/python3.9/site-packages/pyard/pyard.py", line 180, in redux_gl
    return self.redux_gl(glstring, redux_type)
  File "/Users/mmaiers/tmp/py-ard/venv/lib/python3.9/site-packages/pyard/pyard.py", line 180, in redux_gl
    return self.redux_gl(glstring, redux_type)
  File "/Users/mmaiers/tmp/py-ard/venv/lib/python3.9/site-packages/pyard/pyard.py", line 180, in redux_gl
    return self.redux_gl(glstring, redux_type)
  [Previous line repeated 491 more times]
  File "/Users/mmaiers/tmp/py-ard/venv/lib/python3.9/site-packages/pyard/pyard.py", line 155, in redux_gl
    if not self.isvalid_gl(glstring):
  File "/Users/mmaiers/tmp/py-ard/venv/lib/python3.9/site-packages/pyard/pyard.py", line 394, in isvalid_gl
    return self.isvalid(glstring)
  File "/Users/mmaiers/tmp/py-ard/venv/lib/python3.9/site-packages/pyard/pyard.py", line 358, in isvalid
    if not self.is_mac(allele) and \
  File "/Users/mmaiers/tmp/py-ard/venv/lib/python3.9/site-packages/pyard/pyard.py", line 246, in is_mac
    return re.search(r":\D+", gl) is not None
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 291, in _compile
    if isinstance(flags, RegexFlag):
RecursionError: maximum recursion depth exceeded in __instancecheck__
```

**Comment by pbashyal-nmdp** [comment]
Thanks, I can reproduce it now.
```
>>> ard.redux_gl('HLA-A*10', 'lgx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pbashyal/bioinformatics/py-ard/pyard/pyard.py", line 180, in redux_gl
    return self.redux_gl(glstring, redux_type)
  File "/Users/pbashyal/bioinformatics/py-ard/pyard/pyard.py", line 180, in redux_gl
    return self.redux_gl(glstring, redux_type)
  File "/Users/pbashyal/bioinformatics/py-ard/pyard/pyard.py", line 180, in redux_gl
    return self.redux_gl(glstring, redux_type)
  [Previous line repeated 492 more times]
```

**Comment by mmaiers-nmdp** [comment]
Note: if its not working for the default instance (ard=pyard.ARD()) try removing the sqllie3 file:

```
 rm ~/.pyard/pyard-Latest.sqlite3 
(venv) A0506268:py-ard mmaiers$ python
Python 3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyard
ard=>>> ard = pyard.ARD()
ard.redux_gl('A10', 'lg')
>>> ard.redux_gl('A10', 'lg')
'A*26:01g/A*26:10g/A*26:15g/A*26:92g/A*66:01g/A*66:03g'
>>> 
```
